# Server
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/flightbooking
spring.datasource.username=postgres
spring.datasource.password=123

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
jwt.secret=404D635166546A576E5A7234753778214125442A472D4B6150645367566B5970
jwt.expiration=86400000